export const userContants = {
  LOGIN_FORM_SET_JSON: "LOGIN_FORM_SET_JSON",
  USER_ROLE_ASSIGN_SET_JSON: "USER_ROLE_ASSIGN_SET_JSON",
  GET_USER__REQUEST: "GET_USER__REQUEST",
  GET_USER__SUCCESS: "GET_USER__SUCCESS",
  SET_UPDATED_ROLE: "SET_UPDATED_ROLE",

  EMAIL_CHECKER_REQUEST: "EMAIL_CHECKER_REQUEST",
  EMAIL_CHECKER_FAILURE: "EMAIL_CHECKER_FAILURE",
  EMAIL_CHECKER_SUCCESS: "EMAIL_CHECKER_SUCCESS",

  CHECK_USER_STATUS_REQUEST: "CHECK_USER_STATUS_REQUEST",
  CHECK_USER_STATUS_SUCCESS: "CHECK_USER_STATUS_SUCCESS",
  CHECK_USER_STATUS_FAILURE: "CHECK_USER_STATUS_FAILURE",

  UPDATE_STATE_REQUEST: "UPDATE_STATE_REQUEST",
  UPDATE_STATE_SUCCESS: "UPDATE_STATE_SUCCESS",

  USER_UPDATE_REQUEST: "USER_UPDATE_REQUEST",
  USER_UPDATE_SUCCESS: "USER_UPDATE_SUCCESS",
};

export const authConstants = {
  LOGIN_FORM_SET_JSON: "LOGIN_FORM_SET_JSON",
};
